package com.rental.car.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.rental.car.model.Car;
import com.rental.car.service.CarLocalServiceUtil;

/**
 * The extended model base implementation for the Car service. Represents a row in the &quot;RC_Car&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CarImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CarImpl
 * @see com.rental.car.model.Car
 * @generated
 */
public abstract class CarBaseImpl extends CarModelImpl implements Car {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a car model instance should use the {@link Car} interface instead.
     */
    public void persist() throws SystemException {
        if (this.isNew()) {
            CarLocalServiceUtil.addCar(this);
        } else {
            CarLocalServiceUtil.updateCar(this);
        }
    }
}
